### ISSUE TITLE
Better example config needed

### ISSUE THREAD

**Issue by Jaff** [ViacomInc/roku_builder#13]
How is it possible to package a project ? Error when I tried running it: 
/var/lib/gems/2.3.0/gems/multipart-post-2.0.0/lib/composite_io.rb:85:in `initialize': No such file or directory @ rb_sysopen - FanTV-Roku.pkg (Errno::ENOENT)
	from /var/lib/gems/2.3.0/gems/multipart-post-2.0.0/lib/composite_io.rb:85:in `open'
	from /var/lib/gems/2.3.0/gems/multipart-post-2.0.0/lib/composite_io.rb:85:in `initialize'
	from /var/lib/gems/2.3.0/gems/roku_builder-3.12.7/lib/roku_builder/keyer.rb:48:in `new'
	from /var/lib/gems/2.3.0/gems/roku_builder-3.12.7/lib/roku_builder/keyer.rb:48:in `rekey'
	from /var/lib/gems/2.3.0/gems/roku_builder-3.12.7/lib/roku_builder/controller_commands.rb:80:in `package'
	from /var/lib/gems/2.3.0/gems/roku_builder-3.12.7/lib/roku_builder/controller.rb:144:in `execute_commands'
	from /var/lib/gems/2.3.0/gems/roku_builder-3.12.7/lib/roku_builder/controller.rb:40:in `run'
	from /var/lib/gems/2.3.0/gems/roku_builder-3.12.7/bin/roku:202:in `<top (required)>'
	from /usr/local/bin/roku:22:in `load'
	from /usr/local/bin/roku:22:in `<main>'

**Comment by greeneca** [comment]
What was the error you got? 

The simplest project would just be an app. If you are just developing one app then you can think of a project as an app. If you have a more complicated setup, for instance a common code base for multiple apps, then what a project is can vary.

**Comment by Jaff** [comment]
I tried running package: ‘roku -ps production’  where my keyed_pkg file did not yet exist. I expected it to be created by the tool.
-- 
Mark Jaffe
jaffe.mark@gmail.com <mailto:jaffe.mark@gmail.com> 
@Jaff
https://github.com/jaff
408-807-2093 (cell)

**Comment by greeneca** [comment]
You can run 'roku --genkey' to generate a keyed_pkg. This in not very clear in the readme. I will update it.

**Comment by Jaff** [comment]
What is supposed to be result of 'roku --genkey' ? Doesn't that affect the device? Isn't it supposed to provide a password?

**Comment by greeneca** [comment]
It should. Try running `roku --genkey -v`.

**Comment by greeneca** [comment]
There is a better description of packaging an app here 

https://github.com/ViacomInc/roku_builder#basic-steps-for-creating-a-roku-channelapplication-package

I have also changed gen key so it will always print the password/pkg path.

**Comment by Jaff** [comment]
Thanks for updates. I think either I am unclear about expectations, or your explanation of the workflow is deceptive. Here are my expectations:
- my build script creates a zip file in current directory
- I call roku tool to sideload current dir for testing. 
- I call roku tool to create signed package for private channel uploading so my testers can exercise the latest build
- I call roku tool to upload the signed package to specified channel

This workflow is currently being implemented in Docker container on our Jenkins CI

**Comment by greeneca** [comment]
Does you build script do anything other then create the zip file? If so then I may need to re work some things. If not then you can skip it. The RokuBuilder will build the zip file its self. 

How you call the the toot to sideload or package depends on your answer to my question.

The tool is not currently able to upload to the Roku portal. There is no API to do this and Roku has reicently added a captcha to the upload process that would prevent the tool from doing it via web scraping.

**Comment by Jaff** [comment]
Charles,

No, it just does a zip with command:

zip -r $buildFile  manifest source locale images fonts components

The file name is composed of a fixed string with versioning embedded, using Jenkins variable $BUILD_NUMBER, for example: FanTV-Roku-1.71.12.zip

I was also able to package the workspace once I understood the correct setting:
          "key": {
            "keyed_pkg": "/tmp/key_890d16d304f04a46cde61c351b77853852fffbc0.pkg",

observed from output of ‘roku --genkey'

One suggestion is to allow setting path to roku_config.json; since the docker image runs as root, it is necessary to copy my checked-in config to /root/ before each build. Allowing me to specify path to current directory would help.
-- 
Mark Jaffe
jaffe.mark@gmail.com <mailto:jaffe.mark@gmail.com> 
@Jaff
https://github.com/jaff
408-807-2093 (cell)

**Comment by greeneca** [comment]
If thats the case you can skip the build script. Just ensure that manifest is in the project "files" config array and source, locale, images, fonts, and components are in the project "folders" config array. 

During development you can run `roku --sideload --working` or `roku -lw` and that will sideload your app into the device. 

For packaging you can run `roku --package --stage production` or `roku -ps production` replacing production with what ever you called the stage. This will rekey the device with the correct key, zip, sideload, and then package the app.

There is a option to define the config file. `roku -ps production --config <path/to/config>` will use the config at path/to/config.

**Comment by greeneca** [comment]
I haven't heard anything on this issue so I am going to close it. If you are still having issues you can reopen.
