### ISSUE TITLE
Publish to channel?

### ISSUE THREAD

**Issue by Jaff** [ViacomInc/roku_builder#14]
We are trying to setup CI (continuous-integration) for our channel and so far I am able to sideload and package. What would it take to allow publishing to a private channel for testing? Would your tool allow pulling the P*.pkg off the device and push to a defined channel?

**Comment by greeneca** [comment]
The tool will pull the pkg file off of the device (it does that during the
package) but unless there is an API that I am not aware of it is not
possible to automatically upload the pkg file to the Roku portal. I would
love to be able to and as soon as an API is available I will. Right now
there is a captcha on the pkg upload preventing it from done automatically.

**Comment by Jaff** [comment]
Where can I find the pkg file? We run in a docker image on Jenkins, and I was told we cannot reference /tmp directory.

**Comment by Jaff** [comment]
discovered --out option

**Comment by Jaff** [comment]
discovered --out option
