### ISSUE TITLE
Issues using in Windows 

### ISSUE THREAD

**Issue by lvcabral** [ViacomInc/roku_builder#15]
I installed successfully on a windows machine, but the following issues I had to workaround:

1. Additional dependency needed: windows security gem:
`gem install win32-security`
2. Create a folder 'tmp' at the root for C: drive 
  Suggestion: the default out folder should be configurable at the config json
3. Change '/dev/null' at line 57 of inspector.rb to 'NUL'
  Suggestion: identify if is windows or unix based system and use the right string

**Comment by greeneca** [comment]
Thanks for testing the gem on windows. Would you be able to pull down master and give it a try. I don't have a windows machine to test on.

**Comment by lvcabral** [comment]
Thanks for fixing these, I will make the test and report the results here

**Comment by lvcabral** [comment]
Your fixes works fine but I had to comment one line on file "roku" line 6:
`#require "byebug"`

Another issue (not related to your changes) is that for some reason the Screenshot file is being created corrupted, I will investigate more and let you guys know.

**Comment by lvcabral** [comment]
With my last pull request this issue can be closed
