### ISSUE TITLE
roku --restart not working/ command not found

### ISSUE THREAD

**Issue by philotas** [ViacomInc/roku_builder#2]
`/Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/roku_builder-3.6.4/bin/roku:170:in`<top (required)>': invalid option: --restart (OptionParser::InvalidOption)`

**Comment by greeneca** [comment]
Yes this option was removed. It was not reliable across different firmware version and didn't always work anyway. If there is a way of making this work consistently then I will add it back in.

**Comment by philotas** [comment]
ok, if it is removed then maybe it should be removed from the Docs or at least there could be a comment, that it is not working at the moment.
