### ISSUE TITLE
Screenshot file is always created with jpg extension

### ISSUE THREAD

**Issue by lvcabral** [ViacomInc/roku_builder#23]
This was closed as issue #19 but I can't reopen it, so I'm creating a new issue
----

Roku allows developers to configure the format for the screenshot file between jpeg and PNG.

To access this configuration screen use:
Home 5x, Up, Right, Down, Left, Up

The gem is always saving the file as jpg even when the Roku is configured to PNG resulting in a file with inconsistency between content and extension

**Comment by greeneca** [comment]
The fix for this is in 4.2.3. Please test and close.

**Comment by lvcabral** [comment]
Tested, it works.
