### ISSUE TITLE
locales seem to be missing

### ISSUE THREAD

**Issue by nmaves** [ViacomInc/roku_builder#25]
First off we love this gem (pun intended) of a tool. 

We ran into an issue today where we could not get our localizations to work when we sideloaded our app with this tool.  If we just zip up our files everything works perfectly.  My best guess is that you are not packaging up the locale directory with the bundle.  

Anyone else run into this issue?

**Comment by nmaves** [comment]
of course I just thought to look in our .roku_config.json....

silly me

**Comment by greeneca** [comment]
Glad you like it. And the you figured out your issue. Happy to help if you run into anything else. There is also a bunch of information in the wiki you can take a look at.
