### ISSUE TITLE
Unknown Validation hex

### ISSUE THREAD

**Issue by olsh** [ViacomInc/roku_builder#27]
When I run the analyzer with the following command:
`roku --analyze --stage production`

The analysis fails with this error:
`FATAL: RokuBuilder::ImplementationError: Unknown Validation hex`

I'm using `roku_builder-4.11.3` on Windows 10 and Roku 3 device.

Thank you for the tools!

**Comment by greeneca** [comment]
Yes, I missed that validation. I will add it today.

**Comment by greeneca** [comment]
This is fixed in 4.11.4
