### ISSUE TITLE
parsing error when manifest has comment or empty line

### ISSUE THREAD

**Issue by philotas** [ViacomInc/roku_builder#3]
EDIT:

BTW:  good and useful tool. Thanks for sharing!

`/Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/roku_builder-3.6.4/lib/roku_builder/manifest_manager.rb:39:in`block (2 levels) in read_manifest': undefined method `chomp' for nil:NilClass (NoMethodError)
    from /Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/roku_builder-3.6.4/lib/roku_builder/manifest_manager.rb:37:in`each_line'
    from /Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/roku_builder-3.6.4/lib/roku_builder/manifest_manager.rb:37:in `block in read_manifest'
    from /Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/roku_builder-3.6.4/lib/roku_builder/manifest_manager.rb:44:in`open'
    from /Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/roku_builder-3.6.4/lib/roku_builder/manifest_manager.rb:44:in `read_manifest'
    from /Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/roku_builder-3.6.4/lib/roku_builder/manifest_manager.rb:31:in`build_version'
    from /Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/roku_builder-3.6.4/lib/roku_builder/loader.rb:30:in `sideload'
    from /Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/roku_builder-3.6.4/lib/roku_builder/controller_commands.rb:48:in`sideload'
    from /Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/roku_builder-3.6.4/lib/roku_builder/controller.rb:133:in `execute_commands'
    from /Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/roku_builder-3.6.4/lib/roku_builder/controller.rb:40:in`run'
    from /Users/username/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/roku_builder-3.6.4/bin/roku:172:in `<top (required)>'
    from /Users/username/.rbenv/versions/2.2.3/bin/roku:23:in`load'
    from /Users/username/.rbenv/versions/2.2.3/bin/roku:23:in `<main>'
`

**Comment by greeneca** [comment]
Can you upload an example manifest?

**Comment by philotas** [comment]
great. the fix works, so I guess you don't need the example manifest anymore.
