### ISSUE TITLE
CLI options not working

### ISSUE THREAD

**Issue by doapp-ryanp** [ViacomInc/roku_builder#6]
Running on osx, ruby 2.4.0

Few bugs, didn't create separate issues because they are all problems with CLI options

1.  **--out** does not work when specifying a dir:

```
roku --config ./roku-build-config.json -bc --debug --out /Users/ryan/projects/roku/out
/Users/ryan/.rvm/gems/ruby-2.4.0/gems/roku_builder-3.11.0/lib/roku_builder/config_manager.rb:131:in `join': no implicit conversion of nil into String (TypeError)
	from /Users/ryan/.rvm/gems/ruby-2.4.0/gems/roku_builder-3.11.0/lib/roku_builder/config_manager.rb:131:in `update_configs'
	from /Users/ryan/.rvm/gems/ruby-2.4.0/gems/roku_builder-3.11.0/lib/roku_builder/controller_commands.rb:118:in `build'
	from /Users/ryan/.rvm/gems/ruby-2.4.0/gems/roku_builder-3.11.0/lib/roku_builder/controller.rb:129:in `execute_commands'
	from /Users/ryan/.rvm/gems/ruby-2.4.0/gems/roku_builder-3.11.0/lib/roku_builder/controller.rb:36:in `run'
	from /Users/ryan/.rvm/gems/ruby-2.4.0/gems/roku_builder-3.11.0/bin/roku:198:in `<top (required)>'
	from /Users/ryan/.rvm/gems/ruby-2.4.0/bin/roku:22:in `load'
	from /Users/ryan/.rvm/gems/ruby-2.4.0/bin/roku:22:in `<main>'
```

2.  **--out** does not work when specifying a full path to zip file (it always writes to `/tmp`):

```
roku --config ./roku-build-config.json -bc --debug --out /Users/ryan/projects/roku/out/app.zip
[2017-01-26 14:21:44.5776 #91199]  INFO: **Build: /tmp/app.zip**
[2017-01-26 14:21:44.5776 #91199]  INFO: App build; staged using current
```
3. Config file attributes `projects.<projectName>.folders` and `projects.<projectName>.files` are not honored.  Running:

```
roku --config ./roku-build-config.json -bc --debug --out /Users/ryan/projects/roku/out/app.zip
```

Produces a zip file that contains other files and folders in my CWD that are NOT listed in the `folders` and `files` attributes.

4. `--out` is ignored when sideloading.  When sideloading I also want to save off the zip file to a path I specify.

### Here is my config: 

```json
{
  "devices": {
    "default": "AAA62V1010BB",
    "AAA62V1010BB": {
      "ip": "x.x.x.x",
      "user": "xxxx",
      "password": "yyyy"
    }
  },
  "projects": {
    "default": "roku",
    "roku": {
      "directory": "",
      "folders": ["components", "config", "images", "source"],
      "files": ["manifest"],
      "excludes": [],
      "app_name": "",
      "stage_method": "script",
      "stages": {
        "production": {
          "branch": "master",
          "script": {
            "stage": "build/prebuild.sh"
          }
        }
      }
    }
  },
  "keys": {

  },
  "input_mapping": {
    "\\e[1~": ["home", "Home"],
    "<": ["rew", "<"],
    ">": ["ff", ">"],
    "=": ["play", "="],
    "\r": ["select", "Enter"],
    "\\e[D": ["left", "Left Arrow"],
    "\\e[C": ["right", "Right Arrow"],
    "\\e[B": ["down", "Down Arrow"],
    "\\e[A": ["up", "Up Arrow"],
    "\t": ["back", "Tab"],
    "": ["replay", ""],
    "*": ["info", "*"],
    "\u007f": ["backspace", "Backspace"],
    "?": ["search", "?"],
    "\\e\r": ["enter", "Alt + Enter"],
    "\\e[5~": ["volumeup", "Page Up"],
    "\\e[6~": ["volumedown", "Page Down"],
    "\\e[4~": ["mute", "End"],
    "": ["channeldown", ""],
    "": ["channelup", ""],
    "": ["tuner", ""],
    "": ["hdmi1", ""],
    "": ["hdmi2", ""],
    "": ["hdmi3", ""],
    "": ["hdmi4", ""],
    "": ["avi", ""]
  }
}
```

**Comment by greeneca** [comment]
Number 1 and 2 are Issues I will look at. Number 3 is not a bug it is documented in the CLI help (-c : Use current directory to sideload or test. Overrides any project config) The option you are looking for is -w or --working. Number 4 is a feature request that I will add. Thank you for the feedback.

**Comment by greeneca** [comment]
Fixes have been added.

**Comment by doapp-ryanp** [comment]
Thanks!

`-w` is giving me an error: `
```
roku --config ./build/roku-build-config.json -bw --debug --out /Users/ryan/projects/roku/out/1042.zip
[2017-01-30 09:46:08.0587 #34986] DEBUG: Configs OK
/Users/ryan/.rvm/gems/ruby-2.4.0/gems/roku_builder-3.11.1/lib/roku_builder/stager.rb:28:in `chdir': No such file or directory @ dir_chdir -  (Errno::ENOENT)
	from /Users/ryan/.rvm/gems/ruby-2.4.0/gems/roku_builder-3.11.1/lib/roku_builder/stager.rb:28:in `stage'
```

From the help docs on `-w` I can't infer what the option does:
` -w, --working                    Use working directory to sideload or test`

I have multiple developers working on my roku app - so specifying the same `projects.<proj-name>.directory` is not possible because each dev has diff directory they have source in.

I want developers to be able to run the `roku` command from their own project dir, and still be able to pick up the `folders` and `files` directives in the json config file.

Is this possible? If not how do you explicitly specify `folders` and `files` from the CLI when sideloading AND when packaging?

**Comment by greeneca** [comment]
I'm just trying to understand the setup you have. You have multiple developers working on the same project and using the same roku_config.json but working in different directories? Is that right?

**Comment by doapp-ryanp** [comment]
Yup that is correct. Dev A has source code in `~/projects/roku`.  Dev B has source code in `~/workspace/roku`

We want to share things that are not individual developer specific from the config file (like `folders`,`files`,`stage_method`,`stages` etc)

**Comment by greeneca** [comment]
I have started a new issue for this Issue #7

**Comment by doapp-ryanp** [comment]
appreciate that. thanks
