### ISSUE TITLE
Sharing common Config elements between users.

### ISSUE THREAD

**Issue by greeneca** [ViacomInc/roku_builder#7]
Feature: share common config options between users on the same system.

Yup that is correct. Dev A has source code in ~/projects/roku. Dev B has source code in ~/workspace/roku

We want to share things that are not individual developer specific from the config file (like folders,files,stage_method,stages etc)

**Comment by greeneca** [comment]
Proposed Changes:

Add optional argument to config (parent_config) that contains a path to json config file that contains shared values. the current config and the parent config are merged before processing.

@doapp-ryanp  would this be sufficient?

**Comment by doapp-ryanp** [comment]
I also have the same request for `keys.<keyid>.keyed_pkg`.  We will store our keyfiles centrally someplace (s3,1password,dropbox etc) but the dir they exist on each developers machine will differ.  Might be nice to have a `--keys-dir` option and/or attribute in user specific config file (`projects.<proj-name>.stages.<stage>.keys_dir`) that specifies the local dir of where keys exist.

Then the path at `keys.<key-id>.keyed_pkg` could be relative to `keys-dir`

**Comment by greeneca** [comment]
New Proposed Changes:

Add parent_config option that will optionally point to config file that current config can be merged with.

Add projects.project_dir that will optionally set a directory that all project paths are relative to.

Add keys.key_dir that will optionally set a directory that all key paths are relative to.

**Comment by greeneca** [comment]
This is done and will be available in 3.12.0
