### ISSUE TITLE
No way to rekey

### ISSUE THREAD

**Issue by doapp-ryanp** [ViacomInc/roku_builder#8]
I was hoping `-k, --key` was the way to issue a rekey, however when I run I get:

```
roku --config ./build/roku-build-config.json -wk --debug
[2017-01-30 15:22:56.6909 #40983] DEBUG: Configs OK
/Users/ryan/.rvm/gems/ruby-2.4.0/gems/multipart-post-2.0.0/lib/composite_io.rb:85:in `initialize': No such file or directory @ rb_sysopen -
```

Here is a use case.

1.  I'm creating a new app so I run `roku --config ./build/roku-build-config.json --genkey --debug`
1.  I update the config JSON file to add the new key info and point my `projects.<proj-id>.stages.production.key` at it.
1.  I then package the app via `roku --config ./build/roku-build-config.json -pw --debug`
1.  I submit it to Roku for certification.
1.  Days/Weeks/Months pass and I want to update my channel.  I want to Rekey my roku device so that I can update the existing channel (my roku has been wiped, another dev got a new roku device, etc).

My real use case is I have one codebase that will be producing MANY roku channels/apps (each app has different branding and different content, but shares the same codebase).  So as you can imagine, if I wan to package 10 apps I need to do each of these steps: uninstall app from roku, rekey, package.  Doing this by hand via the web interface, or even worse the eclipse plugin would be terrible.

It would be wonderful if there was an "--update" command that did all this for you, as seems like update is a pretty common scenario for anyone maintaining an roku channel.

**Comment by doapp-ryanp** [comment]
Sorry looks like I had an invalid path in the `keyed_pkg` attr.

`--update` option would still be cool but I can work with what exists I think

**Comment by greeneca** [comment]
When you package an app, if you have a key attached to it, then it will
automatically rekey the device with the correct key. You should be able to
see it if you run in debug or verbose mode. Is this what you are looking for?

**Comment by doapp-ryanp** [comment]
yes this is exactly what I was looking for. thanks @greeneca. I'll do a PR to update the readme
